/**
 * Runs the shipped sample sheets through the importer.
 *
 * These files exist so a person can try the feature by hand, which means they
 * are documentation — and documentation that nothing checks goes stale. This
 * asserts each sample still behaves the way its description claims, so a change
 * to the parser cannot quietly turn "8 rows import cleanly" into a lie.
 */
import { describe, it, expect, beforeEach } from 'vitest';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { openDatabase, type DB } from '../src/main/db/connection.js';
import { analyseItemSheet, commitItemImport } from '../src/main/import/itemImport.js';

const DIR = resolve('docs/samples');
const sample = (f: string) => resolve(DIR, f);

let db: DB;

beforeEach(() => {
  db = openDatabase({ filename: ':memory:' });
  db.prepare(
    `INSERT INTO users (id, username, display_name, pin_hash, role) VALUES (1,'owner','Owner','x','OWNER')`,
  ).run();
});

// The samples are generated by scripts/make-sample-sheets.mjs. Skip rather than
// fail when they have not been generated in this checkout.
const haveSamples = existsSync(sample('1-typical-stock.xlsx'));
const describeSamples = haveSamples ? describe : describe.skip;

describeSamples('the shipped sample sheets', () => {
  it('1 — a typical stock list imports every row', () => {
    const res = analyseItemSheet(db, { filePath: sample('1-typical-stock.xlsx') });
    expect(res.errorRows).toBe(0);
    expect(res.okRows).toBe(9); // 10 data rows, one of which is blank and dropped
    expect(res.totalRows).toBe(9);

    // The awkward headers must all be recognised without manual mapping.
    expect(res.missingRequired).toEqual([]);
    expect(res.mapping).toMatchObject({
      tagNumber: 'Tag No.',
      name: 'Particulars',
      productType: 'Category',
      purity: 'Purity',
      grossWeight: 'Gross Wt (gms)',
      netWeight: 'Net Wt (gms)',
      makingRate: 'Making /gm',
    });

    const commit = commitItemImport(db, 1, {
      filePath: sample('1-typical-stock.xlsx'),
      postOpeningStock: true,
    });
    expect(commit.imported).toBe(9);

    // "1,200" must have been read as rupees, not as the number 1.
    const ring = db
      .prepare(`SELECT making_rate_paisa, gross_mg, net_mg FROM items WHERE tag_number='R-101'`)
      .get();
    expect(ring).toEqual({ making_rate_paisa: 120_000, gross_mg: 4_250, net_mg: 3_900 });

    // The six-piece silver lot is tracked as a LOT, not as one item.
    const lot = db
      .prepare(`SELECT i.tracking_mode, b.pieces FROM items i
                JOIN item_balances b ON b.item_id=i.id WHERE i.tag_number='B-500'`)
      .get();
    expect(lot).toEqual({ tracking_mode: 'LOT', pieces: 6 });
  });

  it('2 — a name-only sheet imports at zero weight', () => {
    const res = analyseItemSheet(db, { filePath: sample('2-names-only.xlsx') });
    expect(res.errorRows).toBe(0);
    expect(res.okRows).toBe(6);
    expect(res.missingRequired).toEqual([]);
    expect(res.rows[0].prepared).toMatchObject({ grossMg: 0, netMg: 0 });
    expect(res.rows[0].warnings.join(' ')).toContain('0');
  });

  it('3 — a price column the importer has no field for is ignored', () => {
    const res = analyseItemSheet(db, { filePath: sample('3-names-and-prices.xlsx') });
    expect(res.errorRows).toBe(0);
    expect(res.okRows).toBe(4);
    // "Sale Price" must not have been bound to anything.
    expect(Object.values(res.mapping)).not.toContain('Sale Price');
    expect(res.mapping.name).toBe('Particulars');
  });

  it('4 — tola weights convert when the sheet unit is set', () => {
    const path = sample('4-weights-in-tola.xlsx');

    // Read as grams (the default) the numbers are wrong but still valid rows.
    const asGrams = analyseItemSheet(db, { filePath: path });
    expect(asGrams.rows[0].prepared?.grossMg).toBe(1_000);

    const asTola = analyseItemSheet(db, { filePath: path, weightUnit: 'tola' });
    expect(asTola.errorRows).toBe(0);
    expect(asTola.rows[0].prepared?.grossMg).toBe(11_664); // one tola
    expect(asTola.rows[1].prepared?.grossMg).toBe(5_832); // half a tola
  });

  it('5 — every mistake is caught and explained, and none of it imports', () => {
    const path = sample('5-with-mistakes.xlsx');
    const res = analyseItemSheet(db, { filePath: path });

    const byName = Object.fromEntries(
      res.rows.map((r) => [r.preview.name || '(no name)', r.errors.join(' ')]),
    );

    expect(byName['Net Heavier Than Gross']).toContain('net weight is greater than gross');
    expect(byName['Unknown Category']).toContain('Spaceship');
    expect(byName['Unknown Purity']).toContain('unknown purity');
    expect(byName['Weight Is A Typo']).toContain('not a number');
    expect(byName['Duplicate Tag One']).toContain('repeated');
    expect(byName['Duplicate Tag Two']).toContain('repeated');
    expect(byName['(no name)']).toContain('item name is empty');

    // The two good rows are still recognised as good.
    expect(byName['Perfectly Fine Ring']).toBe('');
    expect(byName['Also Perfectly Fine']).toBe('');

    // Importing the whole sheet must write nothing at all.
    expect(() => commitItemImport(db, 1, { filePath: path, postOpeningStock: true })).toThrow();
    expect(db.prepare('SELECT count(*) c FROM items').get()).toEqual({ c: 0 });

    // Importing only the good rows works.
    const good = res.rows.filter((r) => r.ok).map((r) => r.rowNumber);
    const commit = commitItemImport(db, 1, {
      filePath: path,
      rowNumbers: good,
      postOpeningStock: true,
    });
    expect(commit.imported).toBe(good.length);
  });

  it('5b — a purity that contradicts its metal column is caught', () => {
    const res = analyseItemSheet(db, {
      filePath: sample('5-with-mistakes.xlsx'),
      sheetName: 'Metal Clash',
    });
    expect(res.rows[0].ok).toBe(false);
    expect(res.rows[0].errors.join(' ')).toContain('does not belong');
    expect(res.rows[1].ok).toBe(true);
  });

  it('6 — a multi-sheet workbook lists its sheets and reads the chosen one', () => {
    const path = sample('6-multiple-sheets.xlsx');
    const first = analyseItemSheet(db, { filePath: path });
    expect(first.sheetNames).toEqual(['Gold', 'Silver', 'Notes']);
    expect(first.sheetName).toBe('Gold');
    expect(first.okRows).toBe(2);

    const silver = analyseItemSheet(db, { filePath: path, sheetName: 'Silver' });
    expect(silver.okRows).toBe(2);
    expect(silver.rows[0].preview.name).toBe('Silver Payal');

    // The prose sheet has no usable columns — it must not pretend to import.
    const notes = analyseItemSheet(db, { filePath: path, sheetName: 'Notes' });
    expect(notes.missingRequired).toContain('name');
  });

  it('7 — unknown headers need a manual mapping, which then works', () => {
    const path = sample('7-unknown-headers.xlsx');

    const guessed = analyseItemSheet(db, { filePath: path });
    expect(guessed.missingRequired).toContain('name');

    const mapped = analyseItemSheet(db, {
      filePath: path,
      mapping: { name: 'Col A', grossWeight: 'Col B', productType: 'Col C' },
    });
    expect(mapped.errorRows).toBe(0);
    expect(mapped.okRows).toBe(3);
    expect(mapped.rows[0].prepared).toMatchObject({
      name: 'Ring Ladies 22K',
      grossMg: 5_250,
    });
  });

  it('8 — the CSV reads exactly like the xlsx', () => {
    const res = analyseItemSheet(db, { filePath: sample('8-typical-stock.csv') });
    expect(res.errorRows).toBe(0);
    expect(res.okRows).toBe(3);
    expect(res.rows[0].prepared).toMatchObject({
      name: 'Ladies Ring Zircon',
      grossMg: 4_250,
      netMg: 3_900,
      makingRatePaisa: 120_000,
    });
  });
});
